### ISSUE TITLE
python error when "sync layer with repository branch"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#30] opened 2016-07-25 13:16 UTC
I frequently get the following

```
Plugin version: 1.0-20160720-342d01cc7f1f2b21a9abe90c346a836a31a1c2c7
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\layeractions.py", line 123, in _syncLayer
    if syncLayer(layer):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\tools\gpkgsync.py", line 90, in syncLayer
    mergeCommitId, importCommitId, conflicts, featureIds = repo.importgeopkg(layer, dlg.branch, dlg.message, user, email, True)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 360, in importgeopkg
    print json.dumps(checker.response, indent=4, sort_keys=True)
IOError: [Errno 9] Bad file descriptor
```

when doing the "sync layer with repository branch" operation. A common way to get it is to "Change to a different version..." go pick an early state of the layer, edit it and do "sync layer with repository branch". After choosing the "message to described this update" and clicking ok, the error pop up.

Doing  the same ("sync layer with repository branch") a second time and no error message and the operation seemingly finishing ok.

**Comment by volaya** [comment] 2016-07-25 14:29
this is caused by a debug line that tries to print a response, but the python console was closed. Should be fixed now

**Closed by volaya** 2016-07-25 14:29 UTC

**Comment by gioman** [comment] 2016-07-25 18:06
Fix confirmed. I'm not able anymore to replicate with the above steps.
